###服务启动端口号
server:
  port: 8002
  tomcat:
    max-threads: 20
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: ashun-order
  ##数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/obei_store_logistics?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka
    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000

###开启Hystrix断路器
feign:
  hystrix:
    enabled: true
#### hystrix禁止服务超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#        timeout:
#          enabled: false

logging:
  level:
    root: INFO
    com.ashun: DEBUG

#mybatis-plus
  mybatis-plus:
    type-aliases-package: com.ashun.myBatis.pojo
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: false
      auto-mapping-behavior: full
