###服务启动端口号
server:
  port: 8001
ashun : 222
###服务名称(服务注册到eureka名称)
spring:
  application:
    ####注册中心应用名称
    name: ashun-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka
    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true



