####端口号
server:
  port: 8888
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8900/eureka
spring:
  application:
    ####注册中心应用名称
    name: config-server
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://gitee.com/caihongshun/spring_cloud_config_test.git
          ####搜索目录
          search-paths:
            - ashun
      ####读取分支      
      label: master


#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh